Hello there Young One, I humbly welcome you to the Afterlife.
...
hmm ...
It seems that you are not actually dead yet but are actually in search for your missing story.
If you do not want to die, then I suggest that you start gathering clues to the life that you lived.
